name: CI

on: push

jobs:
  fe-test:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel
        uses: styfle/cancel-workflow-action@0.11.0
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install deps
        run: |
          cd frontend
          npm i
      - name: run test
        run: |
          cd frontend 
          npm run test
  be-test:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel
        uses: styfle/cancel-workflow-action@0.11.0
      - uses: actions/checkout@v3
      - name: Download Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
        id: go
      - name: Get dependencies
        run: go get -v -t -d ./...
      - name: Run tests
        run: |
          cd backend
          go test -v ./... -gcflags=-l
